ColumnMaps:
 tenantId: [ch.chandigarh]
 columnConfig:
   - applicationType: PETNOC
     status: [APPROVED]
     roles: [CITIZEN]
     emailSubject: Application Approved
     template: Dear [:applicantName:],<br/><p>Your application id - [:applicationId:] for permission for keeping of Pets has been approved. Kindly visit the MCC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:],Your application id [:applicationId:] for permission for Keeping of Pets has been approved. Kindly visit the MCC Chandigarh portal for details.
     
   - applicationType: PETNOC
     status: [REJECTED]
     roles: [CITIZEN]
     emailSubject: Application Rejected
     template: Dear [:applicantName:],<br/><p>Your application id - [:applicationId:] for permission for keeping of Pets has been rejected. Kindly visit the MCC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:],Your application id [:applicationId:] for permission for Keeping of Pets has been rejected. Kindly visit the MCC Chandigarh portal for details.

   - applicationType: PETNOC
     status: [PAID]
     roles: [CITIZEN]
     emailSubject: Application Submitted
     template: Dear [:applicantName:],<br/><p>Thank you for submitting online application for permission of keeping pets at Chandigarh Municipal Corporation portal. Your Application id - [:applicationId:] .You can log on to the MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], Your application ID - [:applicationId:] has been received for permission of Keeping pets. Please login to MCC portal for details.
   
   - applicationType: PETNOC
     status: [REASSIGN]
     roles: [CITIZEN]
     emailSubject: Application Required Information
     template: Dear [:applicantName:],<br/><p>You are requested to provide additional clarification as requested by the Department against your application id [:applicationId:] for permission of Keeping pets. Please login to MCC portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], you are requested to provide clarification for your application id [:applicationId:] for permission of Keeping pets. Please visit MCC portal for details.

   - applicationType: SELLMEATNOC
     status: [PAID]
     roles: [CITIZEN]
     emailSubject: Application Submitted
     template: Dear [:applicantName:],<br/><p>Thank you for submitting online application for permission to sell meat at Chandigarh Municipal Corporation portal.Your Application id - [:applicationId:] .You can log on to the MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], Your application ID - [:applicationId:] has been received for permission to sell meat. Please login to MCC portal for details.

   - applicationType: SELLMEATNOC
     status: [APPROVED]
     roles: [CITIZEN]
     emailSubject: Application Approved
     template: Dear [:applicantName:],<br/><p>Your application id - [:applicationId:]  for permission to sell meat has been approved. Kindly visit the MCC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], Your application ID - [:applicationId:]  for permission to sell meat has been approved. Kindly visit the MCC Chandigarh portal for details.

   - applicationType: SELLMEATNOC
     status: [REJECTED]
     roles: [CITIZEN]
     emailSubject: Application Rejected
     template: Dear [:applicantName:],<br/><p>Your application id - [:applicationId:]  for permission to sell meat has been rejected. Kindly visit the MCC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], Your application ID - [:applicationId:]  for permission to sell meat has been  rejected. Kindly visit the MCC Chandigarh portal for details..
     
   - applicationType: SELLMEATNOC
     status: [REASSIGN]
     roles: [CITIZEN]
     emailSubject: Application Required Information
     template: Dear [:applicantName:],<br/><p>You are requested to provide additional clarification as requested by the Department against your application id [:applicationId:] for permission to sell meat. Please login to MCC portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], you are requested to provide clarification for your application id [:applicationId:] for permission to sell meat. Please visit MCC portal for details.
   
   - applicationType: ROADCUTNOC
     status: [INITIATED,INITIATED_TELECOM]
     roles: [CITIZEN]
     emailSubject: Application Submitted
     template: Dear [:applicantName:],<br/><p>Thank you for submitting online application for permission for Road Cut at Chandigarh Municipal Corporation portal. Your Application id - [:applicationId:] .You can log on to the MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], Your application ID - [:applicationId:] has been received for permission for Road Cut. Please login to MCC portal for details

   - applicationType: ROADCUTNOC
     status: [REASSIGN]
     roles: [CITIZEN]
     emailSubject: Application Required Information
     template: Dear [:applicantName:],<br/><p>You are requested to provide additional clarification as requested by the Department against your application ID - [:applicationId:] for Permission for Road Cut. Please login to MCC portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate:  Dear [:applicantName:], you are requested to provide clarification for your application ID - [:applicationId:] for Permission for Road Cut. Please visit MCC portal for details.

   - applicationType: ROADCUTNOC
     status: [VERIFY AFTER APPROVAL L3]
     roles: [CITIZEN]
     emailSubject: Application Approved
     template: Dear [:applicantName:],<br/><p>Your application ID - [:applicationId:] for Permission for Road Cut is approved. Kindly pay the requisite Road cut charges including GST and bank guarantee by visiting MCC Chandigarh portal.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], as per your application ID - [:applicationId:] for road cut permission is approved,Kindly pay the requisite Road cut charges including GST and bank guarantee by visiting MCC Chandigarh portal.

   - applicationType: ROADCUTNOC
     status: [REJECTED]
     roles: [CITIZEN]
     emailSubject: Application Rejected
     template: Dear [:applicantName:],<br/><p> Dear Applicant<br/><p>Your application ID - [:applicationId:] for Permission for Road Cut is rejected. Kindly visit MCC Chandigarh portal.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], as per your application ID - [:applicationId:] for road cut permission is rejected, Kindly visit MCC Chandigarh portal.

   - applicationType: ROADCUTNOC
     status: [PAID]
     roles: [CITIZEN]
     emailSubject: Application Payment Success
     template: Dear [:applicantName:],<br/><p>Please visit to the respective Road division with the original Bank Guarantee document for Road cut Permission letter of your application ID - [:applicationId:] .</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:],Please visit to the respective Road division with the original Bank Guarantee document for Road cut Permission letter of your application ID - [:applicationId:].
 
   - applicationType: ROADCUTNOC
     status: [REVIEWSDE L1,REVIEWOFJE,REVIEWSDE L2,REVIEWOFEE L2,VERIFYHDMEE L1,VERIFYHDMEE L2,VERIFYDMEE,REVIEWOFEE L3,REVIEWOFSE L1,VERIFYCHDSE L1,VERIFYCHDSE L2,VERIFYDMSE,REVIEWOFSE L2,REVIEWOFCE L1,VERIFYDMCE,VERIFYCHDCE L1,VERIFYCHDCE L2,REVIEWOFSDEHQ,REVIEWOFWD,PENDINGAPPROVAL,VERIFY AFTER APPROVAL L1,VERIFY AFTER APPROVAL L2]
     roles: [JE]
     emailSubject: Road cut Application
     template: Dear Employee,<br/><p> This is inform you that application ID - [:applicationId:] has been forwarded to you. Kindly take necessary action.</p><br/>Regards,<br/>Roads department,<br/> Chandigarh Smart City Ltd.
     smsTemplate: Dear Employee,This is inform you that application ID - [:applicationId:] has been forwarded to you. Kindly take necessary action.Regards,Roads department,Chandigarh Smart City Ltd.

   - applicationType: ROADCUTNOC
     status: [REASSIGNTOJE,REASSIGNTOSDE L2,REASSIGNTODMEE,REASSIGNTOHDMEE,REASSIGNTOEE L3,REASSIGNTOCHDSE,REASSIGNTODMSE,REASSIGNTOSE L2,REASSIGNTOWD,REASSIGNTOCHDCE,REASSIGNTODMCE,REASSIGNTOSDEHQ]
     roles: [JE]
     emailSubject: Road cut Application
     template: Dear Employee,<br/><p> This is inform you that application ID - [:applicationId:] has been reassigned to you. Kindly take necessary action.</p><br/>Regards,<br/>Roads department,<br/> Chandigarh Smart City Ltd.
     smsTemplate: Dear Employee,This is inform you that application ID - [:applicationId:] has been reassigned to you. Kindly take necessary action.Regards,Roads department,Chandigarh Smart City Ltd.

   - applicationType: ROADCUTNOC
     status: [INITIATED]
     roles: [EE]
     emailSubject: Road cut Application
     template: Dear Employee,<br/><p> This is inform you that application ID - [:applicationId:] has been forwarded to you. Kindly take necessary action.</p><br/>Regards,<br/>Roads department,<br/> Chandigarh Smart City Ltd.
     smsTemplate: Dear Employee,This is inform you that application ID - [:applicationId:] has been forwarded to you. Kindly take necessary action.Regards,Roads department,Chandigarh Smart City Ltd.
 
   - applicationType: ADVERTISEMENTNOC
     status: [UPDATE]
     roles: [JEX,SUPERINTENDENT,CA]
     emailSubject: Revised Fees For Advertisement 
     template: Respected Sir/ Mam,<br/><p>This is to inform you that advertisement fees has been revised in the Chandigarh Municipality portal. Please visit MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: ""
     
   - applicationType: ADVERTISEMENTNOC
     status: [APPROVED]
     roles: [CITIZEN]
     emailSubject: Application Approved
     template: Dear [:applicantName:],<br/><p>Your application id - [:applicationId:]  for Permission for Advertisement has been approved. Kindly pay the requisite charges by visiting MCC Chandigarh portal.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], Your application id [:applicationId:] for Permission for Advertisement has been approved. Kindly pay the requisite charges by visiting MCC Chandigarh portal.
   
   - applicationType: ADVERTISEMENTNOC
     status: [REJECTED]
     roles: [CITIZEN]
     emailSubject: Application Rejected
     template: Dear [:applicantName:]<br/><p>, Your application id - [:applicationId:]  for Permission for Advertisement has been rejected. Kindly visit the MCC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], Your application id [:applicationId:] for Permission for Advertisement has been rejected. Kindly visit the MCC Chandigarh portal for details. 

   - applicationType: ADVERTISEMENTNOC
     status: [INITIATED,INITIATEDEXC]
     roles: [CITIZEN]
     emailSubject: Application Submitted
     template: Dear [:applicantName:],<br/><p>Thank you for submitting online application for Permission for Advertisement at Chandigarh Municipal Corporation portal. Your Application id - [:applicationId:] .You can log on to the MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], Your application ID - [:applicationId:]  has been received for Permission for Advertisement. Please login to MCC portal for details.

   - applicationType: ADVERTISEMENTNOC
     status: [REASSIGN]
     roles: [CITIZEN]
     emailSubject: Application Required Information
     template: Dear [:applicantName:],<br/><p>You are requested to provide additional clarification as requested by the Department against your application id [:applicationId:] for Permission for Advertisement. Please login to MCC portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], you are requested to provide clarification for your application id [:applicationId:]  for Permission for Advertisement. Please visit MCC portal for details

   - applicationType: ADVERTISEMENTNOC
     status: [WITHDRAW,WITHDRAWAFTERAPRROVAL]
     roles: [CITIZEN]
     emailSubject: Application Withdraw Information
     template: Dear [:applicantName:],<br/><p>Withdrawal request has been submitted for your application ID - [:applicationId:] for Permission for Advertisement. Refund amount is in under processing if any. Kindly visit the MCC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear [:applicantName:], Withdrawal request has been submitted for your application ID - [:applicationId:] for Permission for Advertisement. Kindly visit the MCC Chandigarh portal for details.

   - applicationType: ADVERTISEMENTNOC
     status: [WITHDRAW,WITHDRAWAFTERAPRROVAL]
     roles: [CA]
     emailSubject: Application Withdraw Information
     template: Respected Sir/ Mam,<br/><p>This is to inform you that Application id -[:applicationId:] for permission of advertisement has been withdrawal by the applicant.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: ""